# Generated by Django 6.1 on 2026-08-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegacyUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_path",
                    models.CharField(
                        help_text="Например /mirrors/halo-moon/",
                        max_length=300,
                        unique=True,
                        verbose_name="старый путь",
                    ),
                ),
                (
                    "new_path",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — страница удалена навсегда (410)",
                        max_length=300,
                        verbose_name="новый путь",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="примечание"
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес старого сайта",
                "verbose_name_plural": "адреса старого сайта",
                "ordering": ("old_path",),
            },
        ),
    ]
