# Generated by Django 6.1 on 2026-08-20 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_product_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="имя")),
                (
                    "phone",
                    models.CharField(max_length=32, verbose_name="телефон"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="комментарий"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("home", "форма на сайте"),
                            ("product", "карточка товара"),
                            ("cart", "корзина"),
                        ],
                        default="home",
                        max_length=10,
                        verbose_name="откуда",
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False, verbose_name="согласие на обработку ПД"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="создана"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, verbose_name="обработана"
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="InquiryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="название"),
                ),
                (
                    "product_price",
                    models.PositiveIntegerField(verbose_name="цена «от», ₽"),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inquiries.inquiry",
                        verbose_name="заявка",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_items",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар заявки",
                "verbose_name_plural": "состав заявки",
                "ordering": ("pk",),
            },
        ),
    ]
