# Generated by Django 6.1 on 2026-08-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="consent_version",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="редакция согласия"
            ),
        ),
    ]
