# Generated by Django 6.1 on 2026-08-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0002_inquiry_consent_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiryitem",
            name="product_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="цена «от», ₽"
            ),
        ),
    ]
