# Generated by Django 6.1 on 2026-08-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0003_alter_inquiryitem_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="calculated_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="посчитанная цена, ₽"
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="configuration",
            field=models.TextField(
                blank=True, verbose_name="конфигурация расчёта"
            ),
        ),
    ]
