# Generated by Django 6.1 on 2026-08-19 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="название"),
                ),
                ("slug", models.SlugField(verbose_name="слаг")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("choice", "выбор из списка"),
                            ("boolean", "да/нет"),
                            ("number", "число"),
                        ],
                        default="choice",
                        max_length=10,
                        verbose_name="тип значения",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "атрибут",
                "verbose_name_plural": "атрибуты",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="название"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="слаг")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=100, verbose_name="значение"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.attribute",
                        verbose_name="атрибут",
                    ),
                ),
            ],
            options={
                "verbose_name": "значение атрибута",
                "verbose_name_plural": "значения атрибута",
                "ordering": ["order", "value"],
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="название"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="слаг")),
                (
                    "price",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="цена «от», ₽",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="описание"),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="артикул"
                    ),
                ),
                (
                    "photo_small",
                    models.ImageField(
                        blank=True,
                        upload_to="products/small/",
                        verbose_name="фото малое",
                    ),
                ),
                (
                    "photo_large",
                    models.ImageField(
                        blank=True,
                        upload_to="products/large/",
                        verbose_name="фото большое",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="опубликован"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, verbose_name="популярное"
                    ),
                ),
                (
                    "is_promo",
                    models.BooleanField(default=False, verbose_name="акция"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_bool",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="да/нет"
                    ),
                ),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="число",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_values",
                        to="catalog.attribute",
                        verbose_name="атрибут",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "value_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_assignments",
                        to="catalog.attributevalue",
                        verbose_name="значение из списка",
                    ),
                ),
            ],
            options={
                "verbose_name": "значение атрибута товара",
                "verbose_name_plural": "атрибуты товара",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото галереи",
                "verbose_name_plural": "галерея",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="attributevalue",
            constraint=models.UniqueConstraint(
                fields=("attribute", "value"),
                name="attribute_value_unique_per_attribute",
            ),
        ),
        migrations.AddConstraint(
            model_name="attribute",
            constraint=models.UniqueConstraint(
                fields=("category", "slug"),
                name="attribute_slug_unique_per_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattribute",
            constraint=models.UniqueConstraint(
                fields=("product", "attribute"),
                name="one_value_per_product_attribute",
            ),
        ),
    ]
