# Generated by Django 6.1 on 2026-08-20 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_product_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="слаг"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="title страницы"
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        max_length=200, verbose_name="заголовок h1"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=300, verbose_name="description"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, verbose_name="текст страницы"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="опубликована"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landings",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "посадочная",
                "verbose_name_plural": "посадочные",
                "ordering": ("order", "heading"),
            },
        ),
        migrations.CreateModel(
            name="LandingCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_bool",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="да/нет"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landing_conditions",
                        to="catalog.attribute",
                        verbose_name="атрибут",
                    ),
                ),
                (
                    "landing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="catalog.landing",
                        verbose_name="посадочная",
                    ),
                ),
                (
                    "value_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landing_conditions",
                        to="catalog.attributevalue",
                        verbose_name="значение из списка",
                    ),
                ),
            ],
            options={
                "verbose_name": "условие посадочной",
                "verbose_name_plural": "условия",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("landing", "attribute"),
                        name="one_condition_per_landing_attribute",
                    )
                ],
            },
        ),
    ]
