# Generated by Django 6.1 on 2026-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_landing_landingcondition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                max_length=120, unique=True, verbose_name="слаг"
            ),
        ),
    ]
