# Generated by Django 6.1 on 2026-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="landing",
            name="cover",
            field=models.ImageField(
                blank=True,
                upload_to="landings/",
                verbose_name="обложка плитки",
            ),
        ),
    ]
