# Generated by Django 6.1 on 2026-08-21 16:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_landing_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_area_m2",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.250"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0")
                            )
                        ],
                        verbose_name="минимальная площадь расчёта, м²",
                    ),
                ),
                (
                    "min_order_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="минимальная сумма заказа, ₽"
                    ),
                ),
            ],
            options={
                "verbose_name": "параметры расчёта",
                "verbose_name_plural": "параметры расчёта",
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="is_customer_editable",
            field=models.BooleanField(
                default=False, verbose_name="меняет покупатель"
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="parents",
            field=models.ManyToManyField(
                blank=True,
                related_name="children",
                to="catalog.attribute",
                verbose_name="существует только при",
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Рубли за единицу; для коэффициента — множитель.",
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))
                ],
                verbose_name="тариф",
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("piece", "за штуку"),
                    ("linear_meter", "за погонный метр"),
                    ("square_meter", "за квадратный метр"),
                    ("factor", "коэффициент"),
                ],
                max_length=12,
                verbose_name="единица расхода",
            ),
        ),
    ]
