# Generated by Django 6.1 on 2026-08-21 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_attribute_tariffs"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="scaled_by_shape",
            field=models.BooleanField(
                default=False, verbose_name="умножается коэффициентом формы"
            ),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width_mm",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="ширина, мм",
                    ),
                ),
                (
                    "height_mm",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="высота, мм",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="цена, ₽"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "values",
                    models.ManyToManyField(
                        blank=True,
                        related_name="variant_selections",
                        to="catalog.attributevalue",
                        verbose_name="значения атрибутов",
                    ),
                ),
            ],
            options={
                "verbose_name": "предпосчитанный вариант",
                "verbose_name_plural": "предпосчитанные варианты",
                "ordering": ("order", "pk"),
            },
        ),
    ]
