# Generated by Django 6.1 on 2026-08-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_attributevalue_scaled_by_shape_productvariant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="цена «от», ₽",
            ),
        ),
    ]
