# Generated by Django 6.1 on 2026-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_price_from_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingsettings",
            name="max_long_side_mm",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 — предела нет. Изделие поворачивают: сверяется длинная сторона с этим пределом, короткая — со следующим.",
                verbose_name="наибольшая сторона изделия, мм",
            ),
        ),
        migrations.AddField(
            model_name="pricingsettings",
            name="max_short_side_mm",
            field=models.PositiveIntegerField(
                default=0, verbose_name="вторая сторона изделия, мм"
            ),
        ),
    ]
