# Generated by Django 6.1 on 2026-08-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_production_size_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="is_filterable",
            field=models.BooleanField(
                default=True,
                help_text="Снятый признак убирает атрибут из фильтров каталога; посадочную по нему тоже не завести.",
                verbose_name="строит фильтр",
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="marks_absence",
            field=models.BooleanField(
                default=False,
                help_text="«Без рамы», «без подсветки»: зависящие атрибуты такое значение родителем не считают.",
                verbose_name="означает отсутствие признака",
            ),
        ),
    ]
