# Generated by Django 6.1 on 2026-08-24 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_dictionary_remap"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="landingcondition",
            name="one_condition_per_landing_attribute",
        ),
    ]
