# Generated by Django 6.1 on 2026-08-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_landing_conditions_or_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hides_calculated_price",
            field=models.BooleanField(
                default=False,
                help_text="Конструктор на карточке остаётся: покупатель выбирает размер и материалы, а цену вместо сайта называет менеджер",
                verbose_name="не показывать цену расчёта",
            ),
        ),
    ]
