# Generated by Django 6.1 on 2026-08-25 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_product_hides_calculated_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialPrice",
            fields=[],
            options={
                "verbose_name": "материал и цена",
                "verbose_name_plural": "материалы и цены",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.attributevalue",),
        ),
    ]
