# Generated by Django 6.1 on 2026-08-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="подпись"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="works/", verbose_name="фото"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="опубликована"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "работа",
                "verbose_name_plural": "наши работы",
                "ordering": ("order", "pk"),
            },
        ),
    ]
