# Generated by Django 6.1 on 2026-08-20 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="опубликовано"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=200, verbose_name="вопрос"),
                ),
                ("answer", models.TextField(verbose_name="ответ")),
            ],
            options={
                "verbose_name": "вопрос и ответ",
                "verbose_name_plural": "вопросы и ответы",
                "ordering": ("order", "pk"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="опубликовано"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="заголовок"),
                ),
                (
                    "text",
                    models.TextField(blank=True, verbose_name="описание"),
                ),
            ],
            options={
                "verbose_name": "акция",
                "verbose_name_plural": "акции",
                "ordering": ("order", "pk"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="опубликовано"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "author",
                    models.CharField(max_length=120, verbose_name="автор"),
                ),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "source",
                    models.CharField(max_length=60, verbose_name="источник"),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, verbose_name="ссылка на источник"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="оценка",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        upload_to="reviews/",
                        verbose_name="фото автора",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
                "ordering": ("order", "pk"),
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="work",
            name="is_published",
            field=models.BooleanField(
                default=False, verbose_name="опубликовано"
            ),
        ),
    ]
