# Generated by Django 6.1 on 2026-08-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_promo_for_existing_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=120, verbose_name="город"),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=200, verbose_name="улица и дом"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Как в tel:, без пробелов и скобок: +79812304050",
                        max_length=20,
                        verbose_name="телефон для ссылки",
                    ),
                ),
                (
                    "phone_display",
                    models.CharField(
                        help_text="Как читает человек: +7 981 230-40-50",
                        max_length=30,
                        verbose_name="телефон как показывать",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="e-mail"),
                ),
                (
                    "hours",
                    models.CharField(
                        help_text="Строка для человека: «Ежедневно, по предварительной записи»",
                        max_length=200,
                        verbose_name="часы работы",
                    ),
                ),
                (
                    "opens",
                    models.TimeField(
                        blank=True,
                        help_text="Пока открытие и закрытие не заданы оба, сайт о расписании молчит.",
                        null=True,
                        verbose_name="открытие для разметки",
                    ),
                ),
                (
                    "closes",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="закрытие для разметки",
                    ),
                ),
                (
                    "telegram",
                    models.URLField(blank=True, verbose_name="Telegram"),
                ),
                (
                    "whatsapp",
                    models.URLField(blank=True, verbose_name="WhatsApp"),
                ),
                ("vk", models.URLField(blank=True, verbose_name="ВКонтакте")),
                (
                    "avito",
                    models.URLField(
                        blank=True,
                        help_text="Источник отзывов студии: ссылка «Смотреть все» в блоке отзывов.",
                        verbose_name="витрина на Avito",
                    ),
                ),
                (
                    "map_embed",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка виджета Яндекс.Карт. Пустая — карты на «Контактах» не будет.",
                        max_length=500,
                        verbose_name="карта шоурума",
                    ),
                ),
            ],
            options={
                "verbose_name": "контакты студии",
                "verbose_name_plural": "контакты студии",
            },
        ),
    ]
